name: Run File Hash Weekly

on:
  schedule:
    - cron: '0 2 * * 0'  # Runs every Sunday at 2:00 am UTC

jobs:
  run-filehash:
    runs-on: windows-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -fsSL http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"

      kibana:
        image: docker.elastic.co/kibana/kibana:8.13.0
        ports:
          - 5601:5601
        options: >-
          --health-cmd "curl -fsSL http://localhost:5601/api/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Wait for Elasticsearch to be ready
      run: |
        for i in {1..20}; do
          curl -fsSL http://localhost:9200/_cluster/health && break
          echo "Waiting for Elasticsearch..."
          Start-Sleep -Seconds 10
        done
      shell: pwsh

    - name: Wait for Kibana to be ready
      run: |
        for i in {1..20}; do
          curl -fsSL http://localhost:5601/api/status && break
          echo "Waiting for Kibana..."
          Start-Sleep -Seconds 10
        done
      shell: pwsh

    - name: Run PowerShell Script
      run: pwsh ./your_script.ps1
      env:
        ES_USERNAME: elastic
        ES_PASSWORD: sPd-zKWyDB7qh3*443gu
